spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-client-id
            client-secret: your-secret
          google:
            client-id: your-client-id
            client-secret: your-secret
          vk:
            client-id: 51661254
            client-secret: kCqCbjr5VYpMHItBZtSu
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: email,notify
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize?revoke=1
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=8.1&fields=photo_max
            user-name-attribute: first_name
          google:
            user-name-attribute: name
          github:
            user-name-attribute: login


  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=KfvYuJQ8
    password: KfvYuJQ8
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres

jwt:
  secret: classpath:certs/private.pem
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 8082